name: ${project.name}
main: com.github.brun0xp.shopguiaddon.Main
version: ${project.version}
description: ${project.description}
author: Brun0XP
depend: [ShopGUIPlus, Vault]
api-version: 1.13

commands:
  centralbank:
    description: Command to see server money
    aliases: [bancocentral]